version: '2'
services:
    mysweetshop-app:
        image: mysweetshop
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysweetshop-mysql:3306/mysweetshop?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mysweetshop-mysql:
        extends:
            file: mysql.yml
            service: mysweetshop-mysql
